### ISSUE TITLE
Running errors on startup - No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by funvill** [koopero/creative.code.charlie.foxtrot#2]
Hello @koopero 

On running for the first time I got the following errors. 

Windows machine, Ubuntu bash, on a x64 bit machine.   

```
make: *** No targets specified and no makefile found.  Stop.
(node:28) UnhandledPromiseRejectionWarning: Error: Called utility returned non-zero exit code
    at maybeWrapAsError (/mnt/c/temp/creative.code.charlie.foxtrot/node_modules/bluebird/js/release/util.js:61:12)
    at /mnt/c/temp/creative.code.charlie.foxtrot/node_modules/bluebird/js/release/nodeback.js:38:50
    at ChildProcess.<anonymous> (/mnt/c/temp/creative.code.charlie.foxtrot/node_modules/loopin-native/src/command.js:35:9)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by koopero** [comment]
Hey @funvill , thanks for the report. I'll looks into [loopin-native](https://github.com/koopero/loopin-native)'s build processes on Windows and Linux to clean things up.
